[Excel] (ExcelApi 1.15) Release ExcelApi 1.15 to GA
OfficeDev/office-js-docs-reference pull request #1247
Opened 2022-05-19 02:36 UTC by alison-mk

2022-05-19 02:39 UTC, opbld33 commented
Docs Build status updates of commit _[fe0fc88](https://github.com/OfficeDev/office-js-docs-reference/commits/fe0fc88af0829b9aaf90b7e64e10129c15947267)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/requirement-sets/excel/excel-api-1-15-requirement-set.md](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/requirement-sets/excel/excel-api-1-15-requirement-set.md) | :x:Error | | [Details](#user-content-f644c3632a171c4c712702d7a7b11e4d-c523ddeb)

<a id="f644c3632a171c4c712702d7a7b11e4d-c523ddeb"></a>
### [docs/requirement-sets/excel/excel-api-1-15-requirement-set.md](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/requirement-sets/excel/excel-api-1-15-requirement-set.md)
 - **Line 17, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/excel-1_15.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0e1871f2-88cb-c16b-6d81-dc80e4f66cef/202205190236391520-1247/BuildReport?accessString=3632dbcf6dda50b105a275bb0b3a46df0cbe5bd17d6b8b91e3acd1fce912b4dc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0e1871f2-88cb-c16b-6d81-dc80e4f66cef?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 23:40 UTC, opbld31 commented
Docs Build status updates of commit _[79c40e5](https://github.com/OfficeDev/office-js-docs-reference/commits/79c40e5e15ba94f7ff69f4da55f545111e80f750)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/requirement-sets/excel/excel-api-1-15-requirement-set.md](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/requirement-sets/excel/excel-api-1-15-requirement-set.md) | :x:Error | | [Details](#user-content-f644c3632a171c4c712702d7a7b11e4d-79b19ad1)

<a id="f644c3632a171c4c712702d7a7b11e4d-79b19ad1"></a>
### [docs/requirement-sets/excel/excel-api-1-15-requirement-set.md](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/requirement-sets/excel/excel-api-1-15-requirement-set.md)
 - **Line 17, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/excel-1_15.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0e1871f2-88cb-c16b-6d81-dc80e4f66cef/202205192338362429-1247/BuildReport?accessString=a10b9f858f12e0cfceb77e284dacf8e318011c56819dbb58ebecc174a6f1ddb4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0e1871f2-88cb-c16b-6d81-dc80e4f66cef?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 18:18 UTC, opbld32 commented
Docs Build status updates of commit _[371b5ab](https://github.com/OfficeDev/office-js-docs-reference/commits/371b5abb1a769a4341abc121b14a7041bcb1c7f1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/requirement-sets/excel/excel-api-1-15-requirement-set.md](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/requirement-sets/excel/excel-api-1-15-requirement-set.md) | :x:Error | | [Details](#user-content-f644c3632a171c4c712702d7a7b11e4d-0a55dada)

<a id="f644c3632a171c4c712702d7a7b11e4d-0a55dada"></a>
### [docs/requirement-sets/excel/excel-api-1-15-requirement-set.md](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/requirement-sets/excel/excel-api-1-15-requirement-set.md)
 - **Line 17, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/excel-1_15.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0e1871f2-88cb-c16b-6d81-dc80e4f66cef/202205201812573904-1247/BuildReport?accessString=f01bb025a09d8522473af761bbedbe8a318d6f0aac9f5e320f0fbf57c90993ae).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0e1871f2-88cb-c16b-6d81-dc80e4f66cef?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 19:02 UTC, opbld32 commented
Docs Build status updates of commit _[e87336e](https://github.com/OfficeDev/office-js-docs-reference/commits/e87336ee358fb0b4368f5456fe55fa3e041b6aea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docs/docfx.json](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartdatasourcetype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartdatasourcetype.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartdatasourcetype?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartfill.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartfill.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartfill?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartseries.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartseries.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartseries?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.compactlayout.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.compactlayout.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.compactlayout?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.datasourcetype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.datasourcetype.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.datasourcetype?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.entitycompactlayout.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.entitycompactlayout.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.entitycompactlayout?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.entityviewlayouts.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.entityviewlayouts.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.entityviewlayouts?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfilldata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfilldata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillloadoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillupdatedata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillupdatedata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.groupshapecollectionloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.groupshapecollectionloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.groupshapecollectionloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapecollectionloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapecollectionloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapecollectionloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapedata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapedata.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapedata?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapeloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapeloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapeloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.pivottable.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.pivottable.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.pivottable?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.pivottablescopedcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.pivottablescopedcollection.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.pivottablescopedcollection?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.range.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.shape.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.shape.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.shape?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.tablerowcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.tablerowcollection.yml) | :white_check_mark:Succeeded | [View [...]

2022-05-20 19:39 UTC, AlexJerabek requested changes
Looks good @alison-mk. There is a missing TOC entry. There should be a new 1.15 requirement set page here:
![image](https://user-images.githubusercontent.com/38896772/169599559-da858dbc-d9a4-40c8-80c8-af129f8a0437.png)

The file to change is /docs/requirement-sets/toc.yml

2022-05-20 19:39 UTC, AlexJerabek commented on docs/requirement-sets/requirement-sets.md
> +|Office 2021 on Windows<br>(one-time purchase)|- TaskPane<br>- Content<br>- [CustomFunctions](excel/custom-functions-requirement-sets.md)<br>- [Add-in Commands](common/add-in-commands-requirement-set
Since Office 2021 already shipped, it shouldn't support the new requirement set.

2022-05-20 19:39 UTC, AlexJerabek commented on docs/requirement-sets/requirement-sets.md
> +|Office 2021 on Mac<br>(one-time purchase)|- TaskPane<br>- Content<br>- [CustomFunctions](excel/custom-functions-requirement-sets.md)<br>- [Add-in Commands](common/add-in-commands-requirement-sets.md
The 2019 Mac section has asterisks by later requirement sets. Should 1.15 have that here too?

2022-05-20 19:39 UTC, AlexJerabek commented on docs/requirement-sets/requirement-sets.md
> +|Office 2021 on Mac<br>(one-time purchase)|- TaskPane<br>- Content<br>- [CustomFunctions](excel/custom-functions-requirement-sets.md)<br>- [Add-in Commands](common/add-in-commands-requirement-sets.md
The 2019 Mac section has asterisks by later requirement sets. Should 1.15 have that here too?

2022-05-20 19:39 UTC, AlexJerabek commented on docs/requirement-sets/requirement-sets.md
> +|Office 2021 on Mac<br>(one-time purchase)|- TaskPane<br>- Content<br>- [CustomFunctions](excel/custom-functions-requirement-sets.md)<br>- [Add-in Commands](common/add-in-commands-requirement-sets.md
Same 2021 comment as above.

2022-05-20 19:39 UTC, AlexJerabek commented on generate-docs/tools/package-lock.json
> +  "lockfileVersion": 1,
Not a big deal, but double check that you have the latest released version of Node.

2022-05-20 21:13 UTC, opbld30 commented
Docs Build status updates of commit _[0437019](https://github.com/OfficeDev/office-js-docs-reference/commits/04370198ba6ccc504c4f4ce97f44acb3ca0d822b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docs/docfx.json](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartdatasourcetype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartdatasourcetype.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartdatasourcetype?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartfill.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartfill.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartfill?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartseries.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartseries.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartseries?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.compactlayout.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.compactlayout.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.compactlayout?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.datasourcetype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.datasourcetype.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.datasourcetype?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.entitycompactlayout.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.entitycompactlayout.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.entitycompactlayout?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.entityviewlayouts.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.entityviewlayouts.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.entityviewlayouts?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfilldata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfilldata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillloadoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillupdatedata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillupdatedata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.groupshapecollectionloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.groupshapecollectionloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.groupshapecollectionloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapecollectionloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapecollectionloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapecollectionloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapedata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapedata.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapedata?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapeloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapeloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapeloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.pivottable.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.pivottable.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.pivottable?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.pivottablescopedcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.pivottablescopedcollection.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.pivottablescopedcollection?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.range.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.shape.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.shape.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.shape?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.tablerowcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.tablerowcollection.yml) | :white_check_mark:Succeeded | [View [...]

2022-05-20 21:39 UTC, opbld33 commented
Docs Build status updates of commit _[2bb094a](https://github.com/OfficeDev/office-js-docs-reference/commits/2bb094ada2134c9ddcf401f5b108f36f07c31600)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docs/docfx.json](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/common/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/docs-ref-autogen/common/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview?view=common-js&branch=pr-en-us-1247) (>=common-js \|\| >=outlook-js-1.1 \|\| >=excel-js-1.1 \|\| onenote-js-1.1 \|\| >=powerpoint-js-1.1 \|\| visio-js-1.1 \|\| >=word-js-1.1)<br/> [View](https://review.docs.microsoft.com/en-us/javascript/api/office/office.actions?view=common-js&branch=pr-en-us-1247) (common-js \|\| <outlook-js-preview \|\| <excel-js-preview \|\| <powerpoint-js-preview \|\| <word-js-preview) |
[docs/docs-ref-autogen/common_preview/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/main/docs/docs-ref-autogen/common_preview/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/office/office.actions?view=common-js-preview&branch=pr-en-us-1247) (common-js-preview \|\| outlook-js-preview \|\| excel-js-preview \|\| onenote-js-1.1 \|\| powerpoint-js-preview \|\| word-js-preview) |
[docs/docs-ref-autogen/excel/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartdatasourcetype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartdatasourcetype.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartdatasourcetype?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartfill.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartfill.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartfill?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.chartseries.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.chartseries.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.chartseries?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.compactlayout.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.compactlayout.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.compactlayout?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.datasourcetype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.datasourcetype.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.datasourcetype?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.entitycompactlayout.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.entitycompactlayout.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.entitycompactlayout?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.entityviewlayouts.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.entityviewlayouts.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.entityviewlayouts?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfilldata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfilldata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillloadoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillupdatedata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.chartfillupdatedata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.groupshapecollectionloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.groupshapecollectionloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.groupshapecollectionloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapecollectionloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapecollectionloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapecollectionloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapedata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapedata.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapedata?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.interfaces.shapeloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.interfaces.shapeloadoptions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.shapeloadoptions?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.pivottable.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.pivottable.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.pivottable?view=excel-js-preview&branch=pr-en-us-1247) (excel-js-preview) |
[docs/docs-ref-autogen/excel/excel/excel.pivottablescopedcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/alison-mk-excelapi115/docs/docs-ref-autogen/excel/excel/excel.pivottablescopedcollection.yml) | :white_check_mark:Succeeded | [View](https://review.do [...]

2022-05-20 21:54 UTC, alison-mk commented
@AlexJerabek approved this PR via internal communication to me following my most recent commit, and approves merging. He wasn't able to select 'Approve' in GitHub because the PR has so many files that GitHub is lagging. Merging this PR.

2022-05-20 21:55 UTC, merged