[Admin] (moniker) Powerpoint 1 2
OfficeDev/office-js-docs-reference pull request #851
Opened 2020-12-04 01:18 UTC by Rick-Kirkham

2020-12-04 01:18 UTC, o365devx commented
Docs Build status updates of commit _[fde4010](https://github.com/OfficeDev/office-js-docs-reference/commits/fde40103ff74f40766c499f2fc0885bb0cb3b53a)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 01:25 UTC, o365devx commented
Docs Build status updates of commit _[fde4010](https://github.com/OfficeDev/office-js-docs-reference/commits/fde40103ff74f40766c499f2fc0885bb0cb3b53a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-js-docs-reference/blob/powerpoint-1-2/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-d902ab53-53045ca9)

<a id="d902ab53-53045ca9"></a>
### [.openpublishing.publish.config.json](https://github.com/OfficeDev/office-js-docs-reference/blob/powerpoint-1-2/.openpublishing.publish.config.json)
 - **[Error-[MonikerRangeMentionedMonikerNotExist](https://review.docs.microsoft.com/en-us/new-hope/specs/ops/conceptual-versioning?branch=master)]** `````Moniker powerpoint-js-1.2 mentioned in moniker range powerpoint-js-1.2 doesn't exist in moniker service. Depot office-docs-ref-javascript content won't be published`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202012040118176070-851%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oM3CKedJjOmQagR6i%2FnfB%2FvbNPG%2BBS9xBQCYGM8pAmA%3D&st=2020-12-04T01%3A20%3A42Z&se=2021-01-04T01%3A25%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0e1871f2-88cb-c16b-6d81-dc80e4f66cef?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:19 UTC, AlexJerabek requested changes

2020-12-07 19:19 UTC, AlexJerabek commented on docs/docfx.json
> +
Minor nit, but your editor seems to add tabs instead of spaces. I only bring this up because some keyboard shortcut sample broke because of it.

2020-12-07 19:19 UTC, AlexJerabek commented on docs/docfx.json
> +      "src": "docs-ref-autogen/powerpoint_1_2",
This (and the other 4 entries) should stay 1.1. You need all these for each and every moniker.

2020-12-07 19:20 UTC, AlexJerabek commented
@Rick-Kirkham Is there an analogous PR for the -pr repo?

2020-12-07 19:40 UTC, AlexJerabek requested changes
I think this is the root of your GenerateDocs issues

2020-12-07 19:40 UTC, AlexJerabek commented on generate-docs/GenerateDocs.cmd
> +call node version-remover ..\api-extractor-inputs-word-release\powerpoint_1_2\powerpoint.d.ts "PowerPointApi 1.2" ..\api-extractor-inputs-powerpoint-release\powerpoint_1_1\powerpoint.d.ts
```suggestion
call node version-remover ..\api-extractor-inputs-powerpoint-release\powerpoint_1_2\powerpoint.d.ts "PowerPointApi 1.2" ..\api-extractor-inputs-powerpoint-release\powerpoint_1_1\powerpoint.d.ts

```

2020-12-07 19:40 UTC, AlexJerabek commented on generate-docs/GenerateDocs.cmd
> +call node version-remover ..\api-extractor-inputs-word-release\powerpoint_1_1\powerpoint.d.ts "PowerPointApi 1.1" .\tool-inputs\powerpoint-base.d.ts
```suggestion
call node version-remover ..\api-extractor-inputs-powerpoint-release\powerpoint_1_1\powerpoint.d.ts "PowerPointApi 1.1" .\tool-inputs\powerpoint-base.d.ts

```

2020-12-07 20:14 UTC, o365devx commented
Docs Build status updates of commit _[8f7ed1b](https://github.com/OfficeDev/office-js-docs-reference/commits/8f7ed1b2ffa34cf6a28b2b4479646772fcf4e4cd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[_dependentPackages/CommonPlugins/tools/JoinTOC.ps1](https://github.com/OfficeDev/office-js-docs-reference/blob/powerpoint-1-2/_dependentPackages/CommonPlugins/tools/JoinTOC.ps1) | :x:Error | | [Details](#user-content-402d9d56-1538c4d1)

<a id="402d9d56-1538c4d1"></a>
### [_dependentPackages/CommonPlugins/tools/JoinTOC.ps1](https://github.com/OfficeDev/office-js-docs-reference/blob/powerpoint-1-2/_dependentPackages/CommonPlugins/tools/JoinTOC.ps1)
 - **Line 108**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/CommonPlugins/tools/JoinTOC.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Detailed error message: Cannot find path 'W:\tlvh-s\docs\docs-ref-autogen\powerpoint_1_2\toc.yml' because it does not exist..`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202012072011464798-851%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p29dcvA5u0huU2J8%2Byw9Cy9vFVYUO4TPcWJZIYKgmRY%3D&st=2020-12-07T20%3A09%3A31Z&se=2021-01-07T20%3A14%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0e1871f2-88cb-c16b-6d81-dc80e4f66cef?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 20:17 UTC, o365devx commented
Docs Build status updates of commit _[8f7ed1b](https://github.com/OfficeDev/office-js-docs-reference/commits/8f7ed1b2ffa34cf6a28b2b4479646772fcf4e4cd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[_dependentPackages/CommonPlugins/tools/JoinTOC.ps1](https://github.com/OfficeDev/office-js-docs-reference/blob/powerpoint-1-2/_dependentPackages/CommonPlugins/tools/JoinTOC.ps1) | :x:Error | | [Details](#user-content-402d9d56-a84d3ec9)

<a id="402d9d56-a84d3ec9"></a>
### [_dependentPackages/CommonPlugins/tools/JoinTOC.ps1](https://github.com/OfficeDev/office-js-docs-reference/blob/powerpoint-1-2/_dependentPackages/CommonPlugins/tools/JoinTOC.ps1)
 - **Line 108**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/CommonPlugins/tools/JoinTOC.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Detailed error message: Cannot find path 'W:\3w01-s\docs\docs-ref-autogen\powerpoint_1_2\toc.yml' because it does not exist..`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202012072011569892-851%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o7gaD18E9PipWeexL8bNGJkMa%2BZdKbhuUV%2FNO3yFaGs%3D&st=2020-12-07T20%3A12%3A04Z&se=2021-01-07T20%3A17%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0e1871f2-88cb-c16b-6d81-dc80e4f66cef?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 21:55 UTC, closed without merging

2021-01-08 18:51 UTC, AlexJerabek commented
@Rick-Kirkham Should we reopen this PR now that 1.2 is coming to DefinitelyTyped?

2021-01-08 20:49 UTC, Rick-Kirkham commented
@AlexJerabek I was planning a whole new PR to avoid headaches if other changes have been made to some of these files in December. My first step will be a "diff" on the files compared to the current version. If my changes are the only ones, then I'll just reopen this PR.